import { createClient } from '@supabase/supabase-js';

const GEMINI_API_URL = 'https://generativelanguage.googleapis.com/v1beta/models';
const DEFAULT_AGENT_MODEL = process.env.GEMINI_AGENT_MODEL || 'gemini-3.1-flash-lite';
const DEFAULT_EMBEDDING_MODEL =
  process.env.GEMINI_EMBEDDING_MODEL || 'gemini-embedding-001';
const MEMORY_TABLE = process.env.AGENT_MEMORY_TABLE || 'agent_memories';
const CUSTOM_BLOCK_LIMIT = 3;

const SUPPORTED_ACTIONS = new Set([
  'set_active_stage',
  'set_prompt_value',
  'set_script_guidance',
  'set_caption_text',
  'set_target_duration',
  'set_variant_count',
  'update_node_params',
  'create_custom_block',
  'update_custom_block',
  'remove_custom_block',
  'queue_transcription',
  'queue_execution',
]);

function normalizeBody(body) {
  if (!body) {
    return {};
  }

  if (typeof body !== 'string') {
    return body;
  }

  return JSON.parse(body || '{}');
}

function cleanText(value) {
  return String(value || '')
    .replace(/\s+/g, ' ')
    .trim();
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function createAction(type, reason, extras = {}) {
  return {
    id: crypto.randomUUID(),
    type,
    reason,
    ...extras,
  };
}

function createCustomBlock(prompt, blockName, blockKind, description, backingCoreNodes) {
  return {
    blockId: crypto.randomUUID(),
    blockName,
    description,
    blockKind,
    schema: {
      inputs: [
        {
          name: 'workflow_context',
          type: 'object',
          required: true,
          description: 'Current graph snapshot and run context.',
        },
      ],
      outputs: [
        {
          name: 'workflow_patch',
          type: 'object',
          required: true,
          description: 'Validated graph mutations generated by the block.',
        },
      ],
      paramsSchema: [
        {
          name: 'intensity',
          type: 'number',
          required: false,
          description: 'How aggressively this block should alter the workflow.',
        },
      ],
    },
    defaultParams: {
      intensity: 0.7,
    },
    internalPlan: [
      'Read the current workflow context.',
      'Apply validated changes to the backing nodes.',
      'Return a graph patch that can be inspected and edited.',
    ],
    editableFields: ['description', 'defaultParams.intensity'],
    provenance: {
      createdFromPrompt: prompt,
      creationReason: description,
      influencedBy: [],
      backingCoreNodes,
    },
  };
}

function fallbackEmbedding(text) {
  const normalized = cleanText(text).toLowerCase();
  const vector = new Array(24).fill(0);

  for (let index = 0; index < normalized.length; index += 1) {
    const bucket = index % vector.length;
    vector[bucket] += normalized.charCodeAt(index) / 255;
  }

  return vector.map((value) => Number(value.toFixed(4)));
}

function cosineSimilarity(left, right) {
  if (!Array.isArray(left) || !Array.isArray(right) || !left.length || !right.length) {
    return 0;
  }

  const length = Math.min(left.length, right.length);
  let dot = 0;
  let leftMagnitude = 0;
  let rightMagnitude = 0;

  for (let index = 0; index < length; index += 1) {
    const leftValue = Number(left[index] || 0);
    const rightValue = Number(right[index] || 0);
    dot += leftValue * rightValue;
    leftMagnitude += leftValue * leftValue;
    rightMagnitude += rightValue * rightValue;
  }

  if (!leftMagnitude || !rightMagnitude) {
    return 0;
  }

  return dot / (Math.sqrt(leftMagnitude) * Math.sqrt(rightMagnitude));
}

function getSupabaseServerClient() {
  if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return null;
  }

  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

async function embedText(text) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return fallbackEmbedding(text);
  }

  try {
    const response = await fetch(`${GEMINI_API_URL}/${DEFAULT_EMBEDDING_MODEL}:embedContent`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-goog-api-key': apiKey,
      },
      body: JSON.stringify({
        content: {
          parts: [{ text }],
        },
        taskType: 'RETRIEVAL_DOCUMENT',
      }),
    });
    const payload = await response.json();

    if (!response.ok) {
      throw new Error(payload.error?.message || 'Embedding request failed.');
    }

    const values = payload.embedding?.values;
    return Array.isArray(values) && values.length ? values : fallbackEmbedding(text);
  } catch {
    return fallbackEmbedding(text);
  }
}

async function retrieveSimilar(prompt, feature) {
  const client = getSupabaseServerClient();
  if (!client) {
    return [];
  }

  try {
    const queryEmbedding = await embedText(prompt);
    const { data, error } = await client
      .from(MEMORY_TABLE)
      .select('id, kind, source, text, tags, embedding')
      .in('feature', [feature, 'shared'])
      .limit(40);

    if (error || !Array.isArray(data)) {
      return [];
    }

    return data
      .map((row) => {
        const embedding = Array.isArray(row.embedding)
          ? row.embedding
          : Array.isArray(row.embedding?.values)
            ? row.embedding.values
            : [];

        return {
          id: row.id,
          kind: row.kind || 'memory',
          source: row.source || 'supabase',
          text: row.text || '',
          similarity: cosineSimilarity(queryEmbedding, embedding),
          tags: Array.isArray(row.tags) ? row.tags : [],
        };
      })
      .filter((row) => row.text)
      .sort((left, right) => right.similarity - left.similarity)
      .slice(0, 5);
  } catch {
    return [];
  }
}

async function persistMemory(feature, prompt, summary, tags = []) {
  const client = getSupabaseServerClient();
  if (!client) {
    return false;
  }

  try {
    const embedding = await embedText(`${prompt}\n${summary}`);
    const { error } = await client.from(MEMORY_TABLE).insert({
      id: crypto.randomUUID(),
      feature,
      kind: 'agent_command',
      source: 'workflow-agent',
      text: `${prompt}\n${summary}`,
      tags,
      embedding,
      created_at: new Date().toISOString(),
    });

    return !error;
  } catch {
    return false;
  }
}

function parseMaybeJson(text) {
  try {
    return JSON.parse(text);
  } catch {
    return null;
  }
}

function parseGeminiPayload(payload) {
  const text = payload?.candidates?.[0]?.content?.parts
    ?.map((part) => ('text' in part ? part.text : ''))
    .join('')
    .trim();

  if (!text) {
    return null;
  }

  return parseMaybeJson(text);
}

function inferVariantCount(prompt) {
  const match = prompt.match(/\b([2-4])\s+variants?\b/i);
  return match ? clamp(Number(match[1]), 1, 4) : 1;
}

function buildDeterministicPlan({ feature, prompt, workflow }) {
  const lowered = prompt.toLowerCase();
  const actions = [];
  const customBlocks = [];
  const notes = [];

  const wantsRun =
    /\b(run|generate|make|create|build|render|optimi[sz]e|use|add)\b/.test(lowered);
  const wantsTranscription =
    feature === 'feature1' &&
    /\b(transcribe|caption|generate|run|analyze)\b/.test(lowered);
  const variantCount = inferVariantCount(prompt);

  if (feature === 'feature2') {
    if (lowered.includes('female voice') || lowered.includes('female')) {
      actions.push(
        createAction('update_node_params', 'Bias the voice node toward an expressive female voice.', {
          targetNodeId: 'voice',
          params: {
            voiceFilterMode: 'expressive-female',
            voicePreference: 'female',
          },
        })
      );
    }

    if (lowered.includes('male voice')) {
      actions.push(
        createAction('update_node_params', 'Bias the voice node toward an expressive male voice.', {
          targetNodeId: 'voice',
          params: {
            voiceFilterMode: 'expressive-male',
            voicePreference: 'male',
          },
        })
      );
    }

    if (lowered.includes('subway surfers')) {
      actions.push(
        createAction('update_node_params', 'Use the built-in Subway Surfers gameplay preset.', {
          targetNodeId: 'gameplay',
          params: {
            gameplayPresetId: 'subway-classic',
          },
        })
      );
      customBlocks.push(
        createCustomBlock(
          prompt,
          'Subway Surfers Router',
          'meme_cutaway_router',
          'Routes the gameplay node toward the built-in Subway Surfers footage after the opening beat.',
          ['gameplay', 'render']
        )
      );
    }

    if (lowered.includes('chaotic') || lowered.includes('stronger hook')) {
      actions.push(
        createAction('set_script_guidance', 'Push the script toward a more chaotic hook and faster escalation.', {
          params: {
            scriptGuidance:
              'Make the hook hit faster, push the pacing harder, and keep the story escalation chaotic but readable.',
          },
        })
      );
      customBlocks.push(
        createCustomBlock(
          prompt,
          'Chaos Amplifier',
          'chaos_amplifier',
          'Turns up hook intensity, pacing pressure, and meme-friendly escalation.',
          ['prompt', 'script', 'caption']
        )
      );
    }

    if (lowered.includes('meme')) {
      customBlocks.push(
        createCustomBlock(
          prompt,
          'Meme Cutaway Router',
          'meme_cutaway_router',
          'Adds meme and cutaway routing notes without breaking the current render graph.',
          ['script', 'gameplay', 'render']
        )
      );
    }
  } else {
    if (lowered.includes('hook')) {
      customBlocks.push(
        createCustomBlock(
          prompt,
          'Hook A/B Test Pack',
          'hook_ab_test_pack',
          'Adds stronger hook comparison logic to the current reel workflow.',
          ['generate', 'hook-filter']
        )
      );
    }

    if (lowered.includes('retention') || lowered.includes('optimi')) {
      customBlocks.push(
        createCustomBlock(
          prompt,
          'Retention Optimizer',
          'retention_optimizer',
          'Scores candidate clips for retention-oriented pacing and framing.',
          ['generate', 'results']
        )
      );
      actions.push(
        createAction('update_node_params', 'Tighten caption density for retention-focused reels.', {
          targetNodeId: 'generate',
          params: {
            captionDensity: 'tight',
            viralStyle: 'aggressive',
          },
        })
      );
    }

    if (lowered.includes('faster')) {
      actions.push(
        createAction('update_node_params', 'Reduce dead air and bias the flow toward faster pacing.', {
          targetNodeId: 'generate',
          params: {
            removeSilences: true,
            cameraMotionPreference: 'dynamic',
          },
        })
      );
    }
  }

  if (variantCount > 1) {
    actions.push(
      createAction('set_variant_count', `Branch the workflow into ${variantCount} bounded candidates.`, {
        params: { count: variantCount },
      })
    );
    notes.push(`Bound candidate generation to ${variantCount} variants.`);
  }

  customBlocks.slice(0, CUSTOM_BLOCK_LIMIT).forEach((block) => {
    actions.push(
      createAction('create_custom_block', `Create the custom block "${block.blockName}".`, {
        customBlock: block,
      })
    );
  });

  actions.push(
    createAction(
      'set_active_stage',
      feature === 'feature2'
        ? 'Focus the prompt node after applying the workflow changes.'
        : 'Focus the generate stage after applying the workflow changes.',
      {
        targetNodeId: feature === 'feature2' ? 'prompt' : 'generate',
      }
    )
  );

  if (wantsTranscription) {
    actions.push(
      createAction('queue_transcription', 'Load or generate transcript data before running the flow.')
    );
  }

  if (wantsRun) {
    actions.push(
      createAction(
        'queue_execution',
        'Run the existing pipeline after the graph updates have been applied.'
      )
    );
  }

  if (!actions.length) {
    actions.push(
      createAction('set_active_stage', 'Keep the currently selected stage active and leave the graph untouched.', {
        targetNodeId: workflow.activeStageId || workflow.selectedNodeId || workflow.nodes[0]?.id || null,
      })
    );
  }

  return {
    summary:
      feature === 'feature2'
        ? 'Planner updated the Feature 2 graph and prepared the existing brainrot pipeline for execution.'
        : 'Planner updated the Feature 1 workflow and prepared the existing reel pipeline for execution.',
    actions,
    customBlocks: customBlocks.slice(0, CUSTOM_BLOCK_LIMIT),
    execution: {
      shouldTranscribe: wantsTranscription,
      shouldRun: wantsRun,
      notes,
    },
  };
}

async function planWithGemini({ feature, prompt, workflow, retrievalHits }) {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return null;
  }

  try {
    const graphSummary = workflow.nodes.map((node) => ({
      id: node.id,
      type: node.type,
      label: node.label,
      isCustom: Boolean(node.isCustom),
      params: node.params,
    }));

    const response = await fetch(`${GEMINI_API_URL}/${DEFAULT_AGENT_MODEL}:generateContent`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-goog-api-key': apiKey,
      },
      body: JSON.stringify({
        systemInstruction: {
          parts: [
            {
              text: [
                'You are a workflow-planning compiler for an existing short-form video app.',
                'You must preserve current workflows and return graph mutations only.',
                'Do not invent unsafe code execution.',
                'Keep custom blocks typed, explainable, and capped at three.',
                'Return JSON only.',
              ].join('\n'),
            },
          ],
        },
        contents: [
          {
            parts: [
              {
                text: JSON.stringify(
                  {
                    feature,
                    prompt,
                    workflow: {
                      feature: workflow.feature,
                      title: workflow.title,
                      selectedNodeId: workflow.selectedNodeId,
                      activeStageId: workflow.activeStageId,
                      metadata: workflow.metadata,
                      nodes: graphSummary,
                    },
                    retrievalHits,
                  },
                  null,
                  2
                ),
              },
            ],
          },
        ],
        generationConfig: {
          responseMimeType: 'application/json',
          responseJsonSchema: {
            type: 'object',
            properties: {
              summary: { type: 'string' },
              actions: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    type: { type: 'string' },
                    targetNodeId: { type: 'string' },
                    reason: { type: 'string' },
                    params: { type: 'object' },
                  },
                  required: ['type', 'reason'],
                },
              },
              customBlocks: {
                type: 'array',
                items: {
                  type: 'object',
                  properties: {
                    blockName: { type: 'string' },
                    description: { type: 'string' },
                    blockKind: { type: 'string' },
                    backingCoreNodes: {
                      type: 'array',
                      items: { type: 'string' },
                    },
                  },
                  required: ['blockName', 'description', 'blockKind'],
                },
              },
              execution: {
                type: 'object',
                properties: {
                  shouldTranscribe: { type: 'boolean' },
                  shouldRun: { type: 'boolean' },
                  notes: {
                    type: 'array',
                    items: { type: 'string' },
                  },
                },
                required: ['shouldTranscribe', 'shouldRun', 'notes'],
              },
            },
            required: ['summary', 'actions', 'customBlocks', 'execution'],
          },
        },
      }),
    });

    const payload = await response.json();
    if (!response.ok) {
      throw new Error(payload.error?.message || 'Gemini planning failed.');
    }

    const parsed = parseGeminiPayload(payload);
    if (!parsed) {
      return null;
    }

    const customBlocks = Array.isArray(parsed.customBlocks)
      ? parsed.customBlocks.slice(0, CUSTOM_BLOCK_LIMIT).map((block) =>
          createCustomBlock(
            prompt,
            cleanText(block.blockName).slice(0, 72) || 'Custom workflow block',
            cleanText(block.blockKind).slice(0, 72) || 'custom_block',
            cleanText(block.description).slice(0, 180) || 'Typed workflow block generated by Gemini.',
            Array.isArray(block.backingCoreNodes) ? block.backingCoreNodes : []
          )
        )
      : [];

    const actions = Array.isArray(parsed.actions)
      ? parsed.actions.map((action) =>
          createAction(cleanText(action.type), cleanText(action.reason), {
            targetNodeId: cleanText(action.targetNodeId) || undefined,
            params: action.params && typeof action.params === 'object' ? action.params : undefined,
          })
        )
      : [];

    customBlocks.forEach((block) => {
      actions.push(
        createAction('create_custom_block', `Create the custom block "${block.blockName}".`, {
          customBlock: block,
        })
      );
    });

    return {
      summary: cleanText(parsed.summary),
      actions,
      customBlocks,
      execution: {
        shouldTranscribe: Boolean(parsed.execution?.shouldTranscribe),
        shouldRun: Boolean(parsed.execution?.shouldRun),
        notes: Array.isArray(parsed.execution?.notes)
          ? parsed.execution.notes.map((note) => cleanText(note)).filter(Boolean)
          : [],
      },
    };
  } catch {
    return null;
  }
}

function validatePlan(plan) {
  const issues = [];
  const actions = Array.isArray(plan.actions) ? plan.actions : [];

  if (!actions.length) {
    issues.push('Planner did not return any graph actions.');
  }

  actions.forEach((action) => {
    if (!SUPPORTED_ACTIONS.has(action.type)) {
      issues.push(`Unsupported action type: ${action.type}`);
    }
  });

  const customBlockCount = actions.filter((action) => action.type === 'create_custom_block').length;
  if (customBlockCount > CUSTOM_BLOCK_LIMIT) {
    issues.push(`Only ${CUSTOM_BLOCK_LIMIT} custom blocks can be created per request.`);
  }

  return {
    ok: issues.length === 0,
    issues,
  };
}

function buildCandidates(prompt, actions, feature) {
  const variantAction = actions.find((action) => action.type === 'set_variant_count');
  const requestedVariants = clamp(Number(variantAction?.params?.count || 1), 1, 4);
  const count = clamp(requestedVariants, 1, 4);
  const lowered = prompt.toLowerCase();
  const candidates = [];

  for (let index = 0; index < count; index += 1) {
    const retentionBias = lowered.includes('retention') ? 0.72 + index * 0.05 : 0.58 + index * 0.04;
    const hookBias = lowered.includes('hook') ? 0.7 + index * 0.03 : 0.54 + index * 0.03;
    const pacingBias = lowered.includes('chaotic') || lowered.includes('faster') ? 0.74 - index * 0.04 : 0.56 + index * 0.02;
    const alignment = 0.66 + Math.min(0.18, actions.length * 0.02);
    const complexity = Math.max(
      0.16,
      0.44 - actions.filter((action) => action.type === 'create_custom_block').length * 0.06 - index * 0.03
    );
    const overall = retentionBias * 0.32 + hookBias * 0.24 + pacingBias * 0.2 + alignment * 0.18 + complexity * 0.06;

    candidates.push({
      id: `${feature}-candidate-${index + 1}`,
      label: `Candidate ${index + 1}`,
      summary:
        index === 0
          ? 'Balanced candidate anchored to the existing workflow.'
          : index === 1
            ? 'Hook-forward candidate with a slightly more aggressive pacing bias.'
            : index === 2
              ? 'Retention-focused candidate with stronger custom-block influence.'
              : 'Safer candidate that minimizes graph complexity while preserving alignment.',
      branchId: `branch-${index + 1}`,
      variantId: `variant-${index + 1}`,
      actions,
      scoreBreakdown: {
        retention: Number(retentionBias.toFixed(4)),
        hook: Number(hookBias.toFixed(4)),
        pacing: Number(pacingBias.toFixed(4)),
        alignment: Number(alignment.toFixed(4)),
        complexity: Number(complexity.toFixed(4)),
        overall: Number(overall.toFixed(4)),
      },
    });
  }

  return candidates;
}

function selectCandidate(candidates) {
  const selected =
    candidates.sort((left, right) => right.scoreBreakdown.overall - left.scoreBreakdown.overall)[0] ||
    null;

  return {
    selectedCandidateId: selected?.id || null,
    objective: 'Maximize retention, hook strength, pacing quality, and prompt alignment.',
    reason: selected
      ? `${selected.label} won because it produced the strongest weighted overall score without exceeding bounded graph complexity.`
      : 'No candidate was produced, so the optimizer selected nothing.',
    constraints: [
      'Keep variant count at or below four.',
      'Keep custom block creation at or below three.',
      'Preserve the current manual pipeline handlers.',
    ],
  };
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  try {
    const body = normalizeBody(req.body);
    const feature = cleanText(body.feature);
    const prompt = cleanText(body.prompt);
    const workflow = body.workflow ?? null;

    if (feature !== 'feature1' && feature !== 'feature2') {
      res.status(400).json({ error: 'Feature must be feature1 or feature2.' });
      return;
    }

    if (!prompt) {
      res.status(400).json({ error: 'Prompt is required.' });
      return;
    }

    if (!workflow || !Array.isArray(workflow.nodes) || !Array.isArray(workflow.edges)) {
      res.status(400).json({ error: 'Workflow graph is required.' });
      return;
    }

    const retrievalHits = await retrieveSimilar(prompt, feature);
    const geminiPlan = await planWithGemini({
      feature,
      prompt,
      workflow,
      retrievalHits,
    });
    const fallbackPlan = buildDeterministicPlan({
      feature,
      prompt,
      workflow,
    });
    const plan = geminiPlan || fallbackPlan;
    const validation = validatePlan(plan);
    const candidates = buildCandidates(prompt, plan.actions, feature);
    const optimization = selectCandidate(candidates);

    await persistMemory(feature, prompt, plan.summary, [
      feature,
      validation.ok ? 'validated' : 'fallback',
    ]);

    res.status(200).json({
      feature,
      model: geminiPlan ? DEFAULT_AGENT_MODEL : 'deterministic-fallback',
      fallbackUsed: !geminiPlan,
      summary: plan.summary,
      validation,
      retrievalHits,
      actions: plan.actions,
      customBlocks: plan.customBlocks,
      candidates,
      optimization,
      execution: plan.execution,
    });
  } catch (error) {
    res.status(500).json({
      error: error instanceof Error ? error.message : 'Agent orchestration failed.',
    });
  }
}
