import { createClient } from '@supabase/supabase-js';
import { embedTextWithFallback, generateStructuredJson } from './llmProvider.js';

const DEFAULT_AGENT_MODEL =
  process.env.OPENROUTER_AGENT_MODEL || 'openai/gpt-5.4';
const DEFAULT_EMBEDDING_MODEL = process.env.OPENROUTER_EMBEDDING_MODEL || 'text-embedding-3-small';
const MEMORY_TABLE = process.env.AGENT_MEMORY_TABLE || 'agent_memories';
const CUSTOM_BLOCK_LIMIT = 3;

const SUPPORTED_ACTIONS = new Set([
  'set_active_stage',
  'set_prompt_value',
  'set_script_guidance',
  'set_caption_text',
  'set_target_duration',
  'set_variant_count',
  'update_node_params',
  'create_custom_block',
  'update_custom_block',
  'remove_custom_block',
  'queue_transcription',
  'queue_execution',
]);

function normalizeBody(body) {
  if (!body) {
    return {};
  }

  if (typeof body !== 'string') {
    return body;
  }

  return JSON.parse(body || '{}');
}

function cleanText(value) {
  return String(value || '')
    .replace(/\s+/g, ' ')
    .trim();
}

function normalizeActionType(value) {
  return cleanText(value)
    .toLowerCase()
    .replace(/[\s-]+/g, '_');
}

function normalizeNodeId(value) {
  return cleanText(value).toLowerCase();
}

function clamp(value, min, max) {
  return Math.min(max, Math.max(min, value));
}

function createAction(type, reason, extras = {}) {
  return {
    id: crypto.randomUUID(),
    type: normalizeActionType(type),
    reason,
    ...extras,
  };
}

function createCustomBlock(prompt, blockName, blockKind, description, backingCoreNodes) {
  return {
    blockId: crypto.randomUUID(),
    blockName,
    description,
    blockKind,
    schema: {
      inputs: [
        {
          name: 'workflow_context',
          type: 'object',
          required: true,
          description: 'Current graph snapshot and run context.',
        },
      ],
      outputs: [
        {
          name: 'workflow_patch',
          type: 'object',
          required: true,
          description: 'Validated graph mutations generated by the block.',
        },
      ],
      paramsSchema: [
        {
          name: 'intensity',
          type: 'number',
          required: false,
          description: 'How aggressively this block should alter the workflow.',
        },
      ],
    },
    defaultParams: {
      intensity: 0.7,
    },
    internalPlan: [
      'Read the current workflow context.',
      'Apply validated changes to the backing nodes.',
      'Return a graph patch that can be inspected and edited.',
    ],
    editableFields: ['description', 'defaultParams.intensity'],
    provenance: {
      createdFromPrompt: prompt,
      creationReason: description,
      influencedBy: [],
      backingCoreNodes,
    },
  };
}

function hasExplicitExecutionRequest(prompt) {
  const lowered = cleanText(prompt).toLowerCase();

  return (
    /\b(run|render|execute)\b/.test(lowered) ||
    /\bgenerate\b[\w\s]{0,24}\b(reel|reels|video|videos|output|outputs|pipeline)\b/.test(lowered) ||
    /\bmake\b[\w\s]{0,24}\b(reel|reels|video|videos|output|outputs)\b/.test(lowered)
  );
}

function hasExplicitTranscriptionRequest(prompt) {
  return /\btranscrib(?:e|ing|ed|ption)\b/i.test(prompt);
}

function inferRequestedGameplayPreset(prompt) {
  const lowered = cleanText(prompt).toLowerCase();

  if (!lowered) {
    return null;
  }

  if (/\bstreet bubbles?\b/.test(lowered)) {
    return 'satisfying-street-bubbles';
  }

  if (/\bminecraft-gameplay\b|\bminecraft gameplay\b|\bminecraft\b/.test(lowered)) {
    return 'minecraft-gameplay';
  }

  if (/\bsubway surfers?\b|\bsubway gameplay\b|\bsubway\b/.test(lowered)) {
    return 'subway-surfers';
  }

  if (/\bice cream\b/.test(lowered)) {
    return 'satisfying-ice-cream';
  }

  if (/\bsoap\b/.test(lowered)) {
    return 'satisfying-soap';
  }

  if (/\bbubbles?\b/.test(lowered)) {
    return 'satisfying-bubbles';
  }

  if (/\bsatisfying\b|\bstock clip\b|\bstock footage\b/.test(lowered)) {
    return 'satisfying-ice-cream';
  }

  if (/\bcustom remote\b|\bremote gameplay\b|\bremote footage\b/.test(lowered)) {
    return 'custom-remote';
  }

  return null;
}

function normalizeGameplayPresetId(value) {
  const lowered = cleanText(value).toLowerCase();

  if (!lowered) {
    return '';
  }

  if (FALLBACK_GAMEPLAY_PRESETS.some((preset) => preset.id === lowered) || lowered === 'custom-remote') {
    return lowered;
  }

  if (
    lowered === 'subway-classic' ||
    lowered === 'subway-speedrun' ||
    lowered === 'subway-finale'
  ) {
    return 'minecraft-gameplay';
  }

  if (/\bstreet bubbles?\b/.test(lowered)) {
    return 'satisfying-street-bubbles';
  }

  if (/\bice cream\b/.test(lowered)) {
    return 'satisfying-ice-cream';
  }

  if (/\bsoap\b/.test(lowered)) {
    return 'satisfying-soap';
  }

  if (/\bbubbles?\b/.test(lowered)) {
    return 'satisfying-bubbles';
  }

  if (/\bcustom\b|\bremote\b/.test(lowered)) {
    return 'custom-remote';
  }

  if (/\bsubway surfers?\b|\bsubway gameplay\b|\bsubway\b/.test(lowered)) {
    return 'subway-surfers';
  }

  if (
    /\bminecraft-gameplay\b|\bminecraft gameplay\b|\bminecraft\b/.test(lowered) ||
    /\bclassic\b|\bspeedrun\b|\bfinale\b|\bfast\b|\bfinal\b|\bdense\b/.test(lowered)
  ) {
    return 'minecraft-gameplay';
  }

  return inferRequestedGameplayPreset(lowered) || normalizeNodeId(lowered);
}

function hasExplicitGameplaySelectionRequest(prompt) {
  return Boolean(inferRequestedGameplayPreset(prompt));
}

function hasExplicitGameplayChangeRequest(prompt) {
  const lowered = cleanText(prompt).toLowerCase();

  return (
    hasExplicitGameplaySelectionRequest(prompt) ||
    /\bgameplays?\b/.test(lowered) ||
    /\bfootage\b/.test(lowered)
  );
}

function sanitizePlanForFeature({ feature, prompt, workflow, plan }) {
  const allowExecution = hasExplicitExecutionRequest(prompt);
  const allowTranscription = feature === 'feature1' && hasExplicitTranscriptionRequest(prompt);
  const allowGameplaySelection =
    feature === 'feature2' &&
    (hasExplicitGameplayChangeRequest(prompt) || wantsDifferentGameplayVariants(prompt));
  const nextActions = Array.isArray(plan.actions)
    ? plan.actions.filter((action) => {
        if (!action || typeof action !== 'object') {
          return false;
        }

        if (action.type === 'queue_execution') {
          return allowExecution;
        }

        if (action.type === 'queue_transcription') {
          return allowTranscription;
        }

        if (
          feature === 'feature2' &&
          action.type === 'update_node_params' &&
          action.targetNodeId === 'gameplay'
        ) {
          return allowGameplaySelection;
        }

        return true;
      })
    : [];

  if (!nextActions.length) {
    nextActions.push(
      createAction(
        'set_active_stage',
        'Keep the workflow focused on the current graph without changing manual generation inputs.',
        {
          targetNodeId:
            workflow.activeStageId || workflow.selectedNodeId || workflow.nodes[0]?.id || null,
        }
      )
    );
  }

  return {
    ...plan,
    actions: nextActions,
    execution: {
      shouldTranscribe: Boolean(plan.execution?.shouldTranscribe && allowTranscription),
      shouldRun: Boolean(plan.execution?.shouldRun && allowExecution),
      notes: Array.isArray(plan.execution?.notes) ? plan.execution.notes : [],
    },
  };
}

function fallbackEmbedding(text) {
  const normalized = cleanText(text).toLowerCase();
  const vector = new Array(24).fill(0);

  for (let index = 0; index < normalized.length; index += 1) {
    const bucket = index % vector.length;
    vector[bucket] += normalized.charCodeAt(index) / 255;
  }

  return vector.map((value) => Number(value.toFixed(4)));
}

function cosineSimilarity(left, right) {
  if (!Array.isArray(left) || !Array.isArray(right) || !left.length || !right.length) {
    return 0;
  }

  const length = Math.min(left.length, right.length);
  let dot = 0;
  let leftMagnitude = 0;
  let rightMagnitude = 0;

  for (let index = 0; index < length; index += 1) {
    const leftValue = Number(left[index] || 0);
    const rightValue = Number(right[index] || 0);
    dot += leftValue * rightValue;
    leftMagnitude += leftValue * leftValue;
    rightMagnitude += rightValue * rightValue;
  }

  if (!leftMagnitude || !rightMagnitude) {
    return 0;
  }

  return dot / (Math.sqrt(leftMagnitude) * Math.sqrt(rightMagnitude));
}

function getSupabaseServerClient() {
  if (!process.env.SUPABASE_URL || !process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return null;
  }

  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

async function embedText(text) {
  try {
    const embedding = await embedTextWithFallback({
      model: DEFAULT_EMBEDDING_MODEL,
      text,
      taskType: 'RETRIEVAL_DOCUMENT',
      provider: 'openrouter',
    });

    return Array.isArray(embedding.values) && embedding.values.length
      ? embedding.values
      : fallbackEmbedding(text);
  } catch {
    return fallbackEmbedding(text);
  }
}

async function retrieveSimilar(prompt, feature) {
  const client = getSupabaseServerClient();
  if (!client) {
    return [];
  }

  try {
    const queryEmbedding = await embedText(prompt);
    const { data, error } = await client
      .from(MEMORY_TABLE)
      .select('id, kind, source, text, tags, embedding')
      .in('feature', [feature, 'shared'])
      .limit(40);

    if (error || !Array.isArray(data)) {
      return [];
    }

    return data
      .map((row) => {
        const embedding = Array.isArray(row.embedding)
          ? row.embedding
          : Array.isArray(row.embedding?.values)
            ? row.embedding.values
            : [];

        return {
          id: row.id,
          kind: row.kind || 'memory',
          source: row.source || 'supabase',
          text: row.text || '',
          similarity: cosineSimilarity(queryEmbedding, embedding),
          tags: Array.isArray(row.tags) ? row.tags : [],
        };
      })
      .filter((row) => row.text)
      .sort((left, right) => right.similarity - left.similarity)
      .slice(0, 5);
  } catch {
    return [];
  }
}

async function persistMemory(feature, prompt, summary, tags = []) {
  const client = getSupabaseServerClient();
  if (!client) {
    return false;
  }

  try {
    const embedding = await embedText(`${prompt}\n${summary}`);
    const { error } = await client.from(MEMORY_TABLE).insert({
      id: crypto.randomUUID(),
      feature,
      kind: 'agent_command',
      source: 'workflow-agent',
      text: `${prompt}\n${summary}`,
      tags,
      embedding,
      created_at: new Date().toISOString(),
    });

    return !error;
  } catch {
    return false;
  }
}

function inferVariantCount(prompt) {
  const lowered = cleanText(prompt).toLowerCase();
  const matches = [...lowered.matchAll(/\b([2-4])(?:\s+(?:different|distinct|separate|unique)){0,2}\s+(?:variants?|videos?|clips?|outputs?)\b/g)];
  const counts = matches
    .map((match) => Number(match[1]))
    .filter((value) => Number.isFinite(value) && value >= 1 && value <= 4);

  return counts.length ? Math.max(...counts) : 1;
}

function inferGameplayVariantCount(prompt) {
  const lowered = cleanText(prompt).toLowerCase();
  const matches = [
    ...lowered.matchAll(/\b([2-4])\s+(?:different\s+|distinct\s+|unique\s+)?gameplays?\b/g),
    ...lowered.matchAll(/\b([2-4])\s+gameplays?\s+for\s+([2-4])\s+(?:different\s+|distinct\s+|unique\s+)?videos?\b/g),
    ...lowered.matchAll(/\b([2-4])\s+videos?\s+with\s+([2-4])\s+(?:different\s+|distinct\s+|unique\s+)?gameplays?\b/g),
  ];

  const counts = matches
    .flatMap((match) => match.slice(1).filter(Boolean))
    .map((value) => Number(value))
    .filter((value) => Number.isFinite(value) && value >= 2 && value <= 4);

  return counts.length ? Math.max(...counts) : 1;
}

function wantsDifferentGameplayVariants(prompt) {
  return inferGameplayVariantCount(prompt) > 1;
}

function hasExplicitVoiceVariantRequest(prompt) {
  const lowered = cleanText(prompt).toLowerCase();

  return (
    /\bdifferent\s+voices?\b/.test(lowered) ||
    /\bunique\s+voices?\b/.test(lowered) ||
    /\bdifferent\s+narrators?\b/.test(lowered) ||
    /\beach\s+(?:video|output|clip|variant)\s+(?:has|needs|uses)\s+(?:a\s+)?different\s+voice\b/.test(
      lowered
    ) ||
    /\bdifferent\s+voice\s+for\s+each\b/.test(lowered)
  );
}

function inferRequestedScriptVariationMode(prompt) {
  const lowered = cleanText(prompt).toLowerCase();

  if (
    /\bsame(?:\s+exact)?\s+script\b/.test(lowered) ||
    /\breuse(?:\s+the)?\s+same\s+script\b/.test(lowered) ||
    /\bone\s+script\b/.test(lowered) ||
    /\bshared\s+script\b/.test(lowered)
  ) {
    return 'same-script';
  }

  if (/\bdifferent\s+scripts?\b/.test(lowered) || /\bunique\s+scripts?\b/.test(lowered)) {
    return 'different-scripts';
  }

  return null;
}

const FALLBACK_GAMEPLAY_PRESETS = [
  { id: 'minecraft-gameplay', label: 'Minecraft Gameplay' },
  { id: 'subway-surfers', label: 'Subway Surfers' },
  { id: 'satisfying-ice-cream', label: 'Satisfying Ice Cream' },
  { id: 'satisfying-bubbles', label: 'Slow Bubbles' },
  { id: 'satisfying-soap', label: 'Foam Soap' },
  { id: 'satisfying-street-bubbles', label: 'Street Bubbles' },
];

function getGameplayPresetCatalog(workflow) {
  const fromMetadata = Array.isArray(workflow?.metadata?.availableGameplayPresets)
    ? workflow.metadata.availableGameplayPresets
    : [];
  const fromGameplayNode = Array.isArray(
    workflow?.nodes?.find((node) => node.id === 'gameplay')?.params?.availableGameplayPresets
  )
    ? workflow.nodes.find((node) => node.id === 'gameplay').params.availableGameplayPresets
    : [];
  const source = fromMetadata.length ? fromMetadata : fromGameplayNode;

  if (!source.length) {
    return FALLBACK_GAMEPLAY_PRESETS;
  }

  return source
    .map((entry) => ({
      id: normalizeNodeId(entry?.id),
      label: cleanText(entry?.label),
    }))
    .filter((entry) => entry.id && entry.label);
}

function describeGameplayPreset(workflow, presetId) {
  return (
    getGameplayPresetCatalog(workflow).find((entry) => entry.id === normalizeGameplayPresetId(presetId))
      ?.label || normalizeGameplayPresetId(presetId)
  );
}

function buildGameplayPresetSequence(workflow, count, preferredFirstPresetId) {
  const catalog = getGameplayPresetCatalog(workflow).filter((entry) => entry.id !== 'custom-remote');
  const ids = catalog.map((entry) => entry.id);
  const preferred = normalizeNodeId(preferredFirstPresetId);
  const ordered = preferred && ids.includes(preferred)
    ? [preferred, ...ids.filter((id) => id !== preferred)]
    : ids;

  return ordered.slice(0, clamp(count, 1, 4));
}

function getVoiceCatalog(workflow) {
  const voiceNode = workflow?.nodes?.find((node) => node.id === 'voice');
  const fromMetadata = Array.isArray(workflow?.metadata?.availableVoices)
    ? workflow.metadata.availableVoices
    : [];
  const fromVoiceNode = Array.isArray(voiceNode?.params?.availableVoices)
    ? voiceNode.params.availableVoices
    : [];
  const source = fromMetadata.length ? fromMetadata : fromVoiceNode;

  if (!source.length) {
    const fallbackVoiceId = cleanText(
      workflow?.metadata?.selectedVoiceId || voiceNode?.params?.selectedVoiceId
    );

    return fallbackVoiceId
      ? [
          {
            id: fallbackVoiceId,
            label: fallbackVoiceId,
            gender: '',
            category: '',
          },
        ]
      : [];
  }

  return source
    .map((entry) => ({
      id: cleanText(entry?.id),
      label: cleanText(entry?.name || entry?.label || entry?.id),
      gender: cleanText(entry?.gender || entry?.labels?.gender),
      category: cleanText(entry?.category),
    }))
    .filter((entry) => entry.id && entry.label)
    .filter(
      (entry, index, list) => list.findIndex((candidate) => candidate.id === entry.id) === index
    );
}

function normalizeVoiceId(workflow, value) {
  const cleaned = cleanText(value).toLowerCase();

  if (!cleaned) {
    return '';
  }

  const match = getVoiceCatalog(workflow).find(
    (entry) => entry.id.toLowerCase() === cleaned || entry.label.toLowerCase() === cleaned
  );

  return match?.id || '';
}

function describeVoice(workflow, voiceId) {
  const normalized = normalizeVoiceId(workflow, voiceId);

  return getVoiceCatalog(workflow).find((entry) => entry.id === normalized)?.label || cleanText(voiceId);
}

function buildVoiceVariantSequence(workflow, count, preferredFirstVoiceId) {
  const catalog = getVoiceCatalog(workflow);
  const ids = catalog.map((entry) => entry.id);
  const preferred = normalizeVoiceId(workflow, preferredFirstVoiceId);

  if (!ids.length) {
    return preferred ? [preferred] : [];
  }

  const ordered = preferred && ids.includes(preferred)
    ? [preferred, ...ids.filter((id) => id !== preferred)]
    : ids;

  return ordered.slice(0, clamp(count, 1, 4));
}

function resolveWorkflowVideoCount(workflow) {
  return clamp(Number(workflow?.metadata?.videoCount || 1), 1, 4);
}

function determineFeature2FocusStage({
  requestedGameplayPreset,
  wantsGameplayVariants,
  wantsVoiceVariants,
  loweredPrompt,
}) {
  if (requestedGameplayPreset || wantsGameplayVariants) {
    return 'gameplay';
  }

  if (wantsVoiceVariants) {
    return 'voice';
  }

  if (loweredPrompt.includes('voice')) {
    return 'voice';
  }

  if (loweredPrompt.includes('caption')) {
    return 'caption';
  }

  if (loweredPrompt.includes('script') || loweredPrompt.includes('hook')) {
    return 'script';
  }

  return 'prompt';
}

function buildUserFacingPlanSummary({ feature, workflow, plan }) {
  const parts = [];

  if (feature === 'feature2') {
    const gameplayAction = plan.actions.find(
      (action) => action.type === 'update_node_params' && action.targetNodeId === 'gameplay'
    );
    const batchAction = plan.actions.find((action) => action.type === 'set_variant_count');
    const promptAction = plan.actions.find((action) => action.type === 'set_prompt_value');
    const scriptAction = plan.actions.find((action) => action.type === 'set_script_guidance');
    const voiceAction = plan.actions.find(
      (action) => action.type === 'update_node_params' && action.targetNodeId === 'voice'
    );
    const createdBlocks = plan.actions
      .filter((action) => action.type === 'create_custom_block' && action.customBlock)
      .map((action) => cleanText(action.customBlock?.blockName))
      .filter(Boolean);

    const gameplayVariantPresetIds = Array.isArray(gameplayAction?.params?.variantGameplayPresetIds)
      ? gameplayAction.params.variantGameplayPresetIds
          .map((presetId) => normalizeGameplayPresetId(presetId))
          .filter(Boolean)
      : [];
    const voiceVariantIds = Array.isArray(voiceAction?.params?.variantVoiceIds)
      ? voiceAction.params.variantVoiceIds
          .map((voiceId) => normalizeVoiceId(workflow, voiceId))
          .filter(Boolean)
      : [];
    const gameplayPresetId =
      gameplayAction?.params?.selectedGameplayPresetId || gameplayAction?.params?.gameplayPresetId;
    const voiceId =
      typeof voiceAction?.params?.selectedVoiceId === 'string'
        ? normalizeVoiceId(workflow, voiceAction.params.selectedVoiceId)
        : '';

    if (gameplayVariantPresetIds.length > 1) {
      const labels = gameplayVariantPresetIds
        .map((presetId) => describeGameplayPreset(workflow, presetId))
        .join(', ');
      parts.push(
        `Configured ${gameplayVariantPresetIds.length} outputs with distinct gameplays: ${labels}.`
      );
    } else if (typeof gameplayPresetId === 'string' && gameplayPresetId) {
      parts.push(`Switched gameplay to ${describeGameplayPreset(workflow, gameplayPresetId)}.`);
    }

    if (typeof batchAction?.params?.count === 'number' || Number(batchAction?.params?.count)) {
      const count = clamp(Number(batchAction.params.count), 1, 4);
      const scriptVariationMode =
        batchAction?.params?.scriptVariationMode === 'same-script' ||
        batchAction?.params?.scriptVariationMode === 'different-scripts'
          ? batchAction.params.scriptVariationMode
          : null;
      parts.push(
        scriptVariationMode === 'same-script'
          ? `Set the batch count to ${count} output${count === 1 ? '' : 's'} and reuse the same script across each one.`
          : scriptVariationMode === 'different-scripts'
            ? `Set the batch count to ${count} output${count === 1 ? '' : 's'} with separate scripts per output.`
            : `Set the batch count to ${count} output${count === 1 ? '' : 's'}.`
      );
    }

    if (promptAction) {
      parts.push('Updated the prompt node.');
    }

    if (scriptAction) {
      parts.push('Updated the script guidance.');
    }

    if (voiceVariantIds.length > 1) {
      parts.push(
        `Assigned distinct voices across ${voiceVariantIds.length} outputs: ${voiceVariantIds
          .map((nextVoiceId) => describeVoice(workflow, nextVoiceId))
          .join(', ')}.`
      );
    } else if (voiceId) {
      parts.push(`Switched voice to ${describeVoice(workflow, voiceId)}.`);
    } else if (voiceAction) {
      parts.push('Adjusted the voice settings.');
    }

    if (createdBlocks.length) {
      parts.push(
        `Created ${createdBlocks.length} custom node${createdBlocks.length === 1 ? '' : 's'}: ${createdBlocks.join(', ')}.`
      );
    }
  }

  return parts.length ? parts.join(' ') : cleanText(plan.summary);
}

function buildDeterministicPlan({ feature, prompt, workflow }) {
  const lowered = prompt.toLowerCase();
  const actions = [];
  const customBlocks = [];
  const notes = [];

  const wantsRun = hasExplicitExecutionRequest(prompt);
  const wantsTranscription = feature === 'feature1' && hasExplicitTranscriptionRequest(prompt);
  const variantCount = inferVariantCount(prompt);
  const gameplayVariantCount = inferGameplayVariantCount(prompt);
  const wantsGameplayVariants = wantsDifferentGameplayVariants(prompt);
  const wantsVoiceVariants = feature === 'feature2' && hasExplicitVoiceVariantRequest(prompt);
  const currentVideoCount = feature === 'feature2' ? resolveWorkflowVideoCount(workflow) : 1;
  const desiredVoiceVariantCount =
    wantsVoiceVariants && variantCount <= 1 ? currentVideoCount : variantCount;
  const desiredVariantCount = Math.max(
    desiredVoiceVariantCount,
    gameplayVariantCount,
    1
  );
  const requestedGameplayPreset =
    feature === 'feature2' ? inferRequestedGameplayPreset(prompt) : null;
  const requestedScriptVariationMode =
    feature === 'feature2' ? inferRequestedScriptVariationMode(prompt) : null;

  if (feature === 'feature2') {
    const gameplayPresetSequence = wantsGameplayVariants
      ? buildGameplayPresetSequence(workflow, desiredVariantCount, requestedGameplayPreset)
      : [];

    if (requestedGameplayPreset || gameplayPresetSequence.length) {
      const primaryGameplayPreset = requestedGameplayPreset || gameplayPresetSequence[0];
      actions.push(
        createAction(
          'update_node_params',
          gameplayPresetSequence.length > 1
            ? `Assign distinct gameplay presets across ${gameplayPresetSequence.length} outputs.`
            : `Switch the gameplay node to ${describeGameplayPreset(workflow, primaryGameplayPreset)}.`,
          {
            targetNodeId: 'gameplay',
            params: {
              selectedGameplayPresetId: primaryGameplayPreset,
              ...(gameplayPresetSequence.length > 1
                ? {
                    variantGameplayPresetIds: gameplayPresetSequence,
                  }
                : {}),
            },
          }
        )
      );
    }

    const voiceVariantSequence = wantsVoiceVariants
      ? buildVoiceVariantSequence(
          workflow,
          desiredVariantCount,
          workflow?.metadata?.selectedVoiceId ||
            workflow?.nodes?.find((node) => node.id === 'voice')?.params?.selectedVoiceId
        )
      : [];

    if (voiceVariantSequence.length > 1) {
      const voiceLabels = voiceVariantSequence
        .map((voiceId) => describeVoice(workflow, voiceId))
        .join(', ');
      actions.push(
        createAction(
          'update_node_params',
          `Assign distinct voices across ${voiceVariantSequence.length} outputs.`,
          {
            targetNodeId: 'voice',
            params: {
              selectedVoiceId: voiceVariantSequence[0],
              variantVoiceIds: voiceVariantSequence,
            },
          }
        )
      );
      customBlocks.push(
        createCustomBlock(
          prompt,
          'Voice Variant Router',
          'voice_variant_router',
          `Routes ${voiceVariantSequence.length} output branches across ${voiceLabels}.`,
          ['voice', 'render']
        )
      );
      notes.push(`Assign a different voice to each output: ${voiceLabels}.`);
    } else if (lowered.includes('female voice') || lowered.includes('female')) {
      actions.push(
        createAction('update_node_params', 'Bias the voice node toward an expressive female voice.', {
          targetNodeId: 'voice',
          params: {
            voiceFilterMode: 'expressive-female',
            voicePreference: 'female',
          },
        })
      );
    }

    if (!voiceVariantSequence.length && lowered.includes('male voice')) {
      actions.push(
        createAction('update_node_params', 'Bias the voice node toward an expressive male voice.', {
          targetNodeId: 'voice',
          params: {
            voiceFilterMode: 'expressive-male',
            voicePreference: 'male',
          },
        })
      );
    }

    if (gameplayPresetSequence.length > 1) {
      const gameplayLabels = gameplayPresetSequence
        .map((presetId) => describeGameplayPreset(workflow, presetId))
        .join(', ');
      customBlocks.push(
        createCustomBlock(
          prompt,
          'Gameplay Variant Router',
          'gameplay_variant_router',
          `Routes ${gameplayPresetSequence.length} output branches across ${gameplayLabels}.`,
          ['gameplay', 'render']
        )
      );
      notes.push(
        `Assign a different gameplay preset to each output: ${gameplayLabels}.`
      );

      if (requestedScriptVariationMode === 'same-script') {
        notes.push('Reuse the same script across all gameplay branches.');
      }
    }

    if (lowered.includes('chaotic') || lowered.includes('stronger hook')) {
      actions.push(
        createAction('set_script_guidance', 'Push the script toward a more chaotic hook and faster escalation.', {
          params: {
            scriptGuidance:
              'Make the hook hit faster, push the pacing harder, and keep the story escalation chaotic but readable.',
          },
        })
      );
      customBlocks.push(
        createCustomBlock(
          prompt,
          'Chaos Amplifier',
          'chaos_amplifier',
          'Turns up hook intensity, pacing pressure, and meme-friendly escalation.',
          ['prompt', 'script', 'caption']
        )
      );
    }

    if (lowered.includes('meme')) {
      customBlocks.push(
        createCustomBlock(
          prompt,
          'Meme Cutaway Router',
          'meme_cutaway_router',
          'Adds meme and cutaway routing notes without breaking the current render graph.',
          ['script', 'gameplay', 'render']
        )
      );
    }
  } else {
    if (lowered.includes('hook')) {
      customBlocks.push(
        createCustomBlock(
          prompt,
          'Hook A/B Test Pack',
          'hook_ab_test_pack',
          'Adds stronger hook comparison logic to the current reel workflow.',
          ['generate', 'hook-filter']
        )
      );
    }

    if (lowered.includes('retention') || lowered.includes('optimi')) {
      customBlocks.push(
        createCustomBlock(
          prompt,
          'Retention Optimizer',
          'retention_optimizer',
          'Scores candidate clips for retention-oriented pacing and framing.',
          ['generate', 'results']
        )
      );
      actions.push(
        createAction('update_node_params', 'Tighten caption density for retention-focused reels.', {
          targetNodeId: 'generate',
          params: {
            captionDensity: 'tight',
            viralStyle: 'aggressive',
          },
        })
      );
    }

    if (lowered.includes('faster')) {
      actions.push(
        createAction('update_node_params', 'Reduce dead air and bias the flow toward faster pacing.', {
          targetNodeId: 'generate',
          params: {
            removeSilences: true,
            cameraMotionPreference: 'dynamic',
          },
        })
      );
    }
  }

  if (desiredVariantCount > 1) {
    actions.push(
      createAction('set_variant_count', `Branch the workflow into ${desiredVariantCount} bounded candidates.`, {
        params: {
          count: desiredVariantCount,
          ...(requestedScriptVariationMode ? { scriptVariationMode: requestedScriptVariationMode } : {}),
        },
      })
    );
    notes.push(`Bound candidate generation to ${desiredVariantCount} variants.`);
  }

  customBlocks.slice(0, CUSTOM_BLOCK_LIMIT).forEach((block) => {
    actions.push(
      createAction('create_custom_block', `Create the custom block "${block.blockName}".`, {
        customBlock: block,
      })
    );
  });

  actions.push(
    createAction(
      'set_active_stage',
      feature === 'feature2'
        ? 'Focus the most relevant Feature 2 node after applying the workflow changes.'
        : 'Focus the generate stage after applying the workflow changes.',
      {
        targetNodeId:
          feature === 'feature2'
            ? determineFeature2FocusStage({
                requestedGameplayPreset,
                wantsGameplayVariants,
                wantsVoiceVariants,
                loweredPrompt: lowered,
              })
            : 'generate',
      }
    )
  );

  if (wantsTranscription) {
    actions.push(
      createAction('queue_transcription', 'Load or generate transcript data before running the flow.')
    );
  }

  if (wantsRun) {
    actions.push(
      createAction(
        'queue_execution',
        'Run the existing pipeline after the graph updates have been applied.'
      )
    );
  }

  if (!actions.length) {
    actions.push(
      createAction('set_active_stage', 'Keep the currently selected stage active and leave the graph untouched.', {
        targetNodeId: workflow.activeStageId || workflow.selectedNodeId || workflow.nodes[0]?.id || null,
      })
    );
  }

  return {
    summary:
      feature === 'feature2'
        ? 'Planner updated the Feature 2 graph and prepared the existing brainrot pipeline for execution.'
        : 'Planner updated the Feature 1 workflow and prepared the existing reel pipeline for execution.',
    actions,
    customBlocks: customBlocks.slice(0, CUSTOM_BLOCK_LIMIT),
    execution: {
      shouldTranscribe: wantsTranscription,
      shouldRun: wantsRun,
      notes,
    },
  };
}

function planHandlesGameplayRequest(plan) {
  const actions = Array.isArray(plan?.actions) ? plan.actions : [];

  return actions.some(
    (action) =>
      (action.type === 'update_node_params' && action.targetNodeId === 'gameplay') ||
      action.type === 'set_variant_count' ||
      action.type === 'create_custom_block'
  );
}

function planHandlesVoiceVariantRequest(plan) {
  const actions = Array.isArray(plan?.actions) ? plan.actions : [];

  return actions.some(
    (action) =>
      action.type === 'update_node_params' &&
      action.targetNodeId === 'voice' &&
      Array.isArray(action.params?.variantVoiceIds) &&
      action.params.variantVoiceIds.length > 1
  );
}

async function planWithWorkflowAgent({ feature, prompt, workflow, retrievalHits }) {
  if (!process.env.OPENROUTER_API_KEY) {
    return null;
  }

  try {
    const graphSummary = workflow.nodes.map((node) => ({
      id: node.id,
      type: node.type,
      label: node.label,
      isCustom: Boolean(node.isCustom),
      params: node.params,
    }));

    const generation = await generateStructuredJson({
      model: DEFAULT_AGENT_MODEL,
      provider: 'openrouter',
      schemaName: 'workflow_agent_plan',
      systemInstruction: [
        'You are a workflow-planning compiler for an existing short-form video app.',
        'You must preserve current workflows and return graph mutations only.',
        'Do not treat manual generation inputs as disposable.',
        'Do not queue execution or transcription unless the user explicitly asks you to run or transcribe.',
        'For feature2, do not change the gameplay preset unless the user explicitly asks for a gameplay or footage change.',
        'If the user asks for multiple videos with different gameplays, set the variant count, update the gameplay node params with variantGameplayPresetIds, and create a gameplay routing custom block.',
        'If the user asks for different voices across multiple outputs, update the voice node params with variantVoiceIds using distinct available voice ids from the workflow graph and create a voice routing custom block.',
        'If the user asks for multiple outputs that should keep the same script, set set_variant_count params.scriptVariationMode to same-script.',
        'When the user asks to modify the flow, prefer custom-block mutations and stage focus updates.',
        'When revising prompt or script guidance, use the current script in workflow metadata when available and prefer small iterative changes over a full concept reset unless the user asks for one.',
        'If the user explicitly asks to switch gameplay, use update_node_params on the gameplay node with params.selectedGameplayPresetId set to the requested preset id.',
        'Do not invent unsafe code execution.',
        'Keep custom blocks typed, explainable, and capped at three.',
        'Return JSON only.',
      ].join('\n'),
      userPrompt: JSON.stringify(
        {
          feature,
          prompt,
          workflow: {
            feature: workflow.feature,
            title: workflow.title,
            selectedNodeId: workflow.selectedNodeId,
            activeStageId: workflow.activeStageId,
            metadata: workflow.metadata,
            nodes: graphSummary,
          },
          retrievalHits,
        },
        null,
        2
      ),
      schema: {
        type: 'object',
        properties: {
          summary: { type: 'string' },
          actions: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                type: { type: 'string' },
                targetNodeId: { type: 'string' },
                reason: { type: 'string' },
                params: { type: 'object' },
              },
              required: ['type', 'reason'],
            },
          },
          customBlocks: {
            type: 'array',
            items: {
              type: 'object',
              properties: {
                blockName: { type: 'string' },
                description: { type: 'string' },
                blockKind: { type: 'string' },
                backingCoreNodes: {
                  type: 'array',
                  items: { type: 'string' },
                },
              },
              required: ['blockName', 'description', 'blockKind'],
            },
          },
          execution: {
            type: 'object',
            properties: {
              shouldTranscribe: { type: 'boolean' },
              shouldRun: { type: 'boolean' },
              notes: {
                type: 'array',
                items: { type: 'string' },
              },
            },
            required: ['shouldTranscribe', 'shouldRun', 'notes'],
          },
        },
        required: ['summary', 'actions', 'customBlocks', 'execution'],
      },
      temperature: 0.2,
    });
    const parsed = generation.data;
    if (!parsed) {
      return null;
    }

    const customBlocks = Array.isArray(parsed.customBlocks)
      ? parsed.customBlocks.slice(0, CUSTOM_BLOCK_LIMIT).map((block) =>
          createCustomBlock(
            prompt,
            cleanText(block.blockName).slice(0, 72) || 'Custom workflow block',
            cleanText(block.blockKind).slice(0, 72) || 'custom_block',
            cleanText(block.description).slice(0, 180) ||
              'Typed workflow block generated by the workflow agent.',
            Array.isArray(block.backingCoreNodes)
              ? block.backingCoreNodes.map((nodeId) => normalizeNodeId(nodeId)).filter(Boolean)
              : []
          )
        )
      : [];

    const actions = Array.isArray(parsed.actions)
      ? parsed.actions.map((action) => {
          const nextParams =
            action.params && typeof action.params === 'object' ? { ...action.params } : undefined;

          if (normalizeNodeId(action.targetNodeId) === 'gameplay' && nextParams) {
            if (typeof nextParams.selectedGameplayPresetId === 'string') {
              nextParams.selectedGameplayPresetId = normalizeGameplayPresetId(
                nextParams.selectedGameplayPresetId
              );
            }

            if (typeof nextParams.gameplayPresetId === 'string') {
              nextParams.gameplayPresetId = normalizeGameplayPresetId(nextParams.gameplayPresetId);
            }

            if (Array.isArray(nextParams.variantGameplayPresetIds)) {
              nextParams.variantGameplayPresetIds = nextParams.variantGameplayPresetIds
                .map((presetId) => normalizeGameplayPresetId(presetId))
                .filter(Boolean);
            }
          }

          if (normalizeNodeId(action.targetNodeId) === 'voice' && nextParams) {
            if (typeof nextParams.selectedVoiceId === 'string') {
              nextParams.selectedVoiceId =
                normalizeVoiceId(workflow, nextParams.selectedVoiceId) || nextParams.selectedVoiceId;
            }

            const rawVariantVoiceIds = Array.isArray(nextParams.variantVoiceIds)
              ? nextParams.variantVoiceIds
              : Array.isArray(nextParams.voiceIds)
                ? nextParams.voiceIds
                : [];

            if (rawVariantVoiceIds.length) {
              nextParams.variantVoiceIds = rawVariantVoiceIds
                .map((voiceId) => normalizeVoiceId(workflow, voiceId))
                .filter(Boolean);
            }
          }

          return createAction(action.type, cleanText(action.reason), {
            targetNodeId: normalizeNodeId(action.targetNodeId) || undefined,
            params: nextParams,
          });
        })
      : [];

    customBlocks.forEach((block) => {
      actions.push(
        createAction('create_custom_block', `Create the custom block "${block.blockName}".`, {
          customBlock: block,
        })
      );
    });

    return {
      summary: cleanText(parsed.summary),
      modelLabel: generation.model,
      provider: generation.provider,
      warning: generation.warning,
      actions,
      customBlocks,
      execution: {
        shouldTranscribe: Boolean(parsed.execution?.shouldTranscribe),
        shouldRun: Boolean(parsed.execution?.shouldRun),
        notes: Array.isArray(parsed.execution?.notes)
          ? parsed.execution.notes.map((note) => cleanText(note)).filter(Boolean)
          : [],
      },
    };
  } catch {
    return null;
  }
}

function validatePlan(plan) {
  const issues = [];
  const actions = Array.isArray(plan.actions) ? plan.actions : [];

  if (!actions.length) {
    issues.push('Planner did not return any graph actions.');
  }

  actions.forEach((action) => {
    if (!SUPPORTED_ACTIONS.has(action.type)) {
      issues.push(`Unsupported action type: ${action.type}`);
    }
  });

  const customBlockCount = actions.filter((action) => action.type === 'create_custom_block').length;
  if (customBlockCount > CUSTOM_BLOCK_LIMIT) {
    issues.push(`Only ${CUSTOM_BLOCK_LIMIT} custom blocks can be created per request.`);
  }

  return {
    ok: issues.length === 0,
    issues,
  };
}

function buildCandidates(prompt, actions, feature) {
  const variantAction = actions.find((action) => action.type === 'set_variant_count');
  const requestedVariants = clamp(Number(variantAction?.params?.count || 1), 1, 4);
  const count = clamp(requestedVariants, 1, 4);
  const lowered = prompt.toLowerCase();
  const candidates = [];

  for (let index = 0; index < count; index += 1) {
    const retentionBias = lowered.includes('retention') ? 0.72 + index * 0.05 : 0.58 + index * 0.04;
    const hookBias = lowered.includes('hook') ? 0.7 + index * 0.03 : 0.54 + index * 0.03;
    const pacingBias = lowered.includes('chaotic') || lowered.includes('faster') ? 0.74 - index * 0.04 : 0.56 + index * 0.02;
    const alignment = 0.66 + Math.min(0.18, actions.length * 0.02);
    const complexity = Math.max(
      0.16,
      0.44 - actions.filter((action) => action.type === 'create_custom_block').length * 0.06 - index * 0.03
    );
    const overall = retentionBias * 0.32 + hookBias * 0.24 + pacingBias * 0.2 + alignment * 0.18 + complexity * 0.06;

    candidates.push({
      id: `${feature}-candidate-${index + 1}`,
      label: `Candidate ${index + 1}`,
      summary:
        index === 0
          ? 'Balanced candidate anchored to the existing workflow.'
          : index === 1
            ? 'Hook-forward candidate with a slightly more aggressive pacing bias.'
            : index === 2
              ? 'Retention-focused candidate with stronger custom-block influence.'
              : 'Safer candidate that minimizes graph complexity while preserving alignment.',
      branchId: `branch-${index + 1}`,
      variantId: `variant-${index + 1}`,
      actions,
      scoreBreakdown: {
        retention: Number(retentionBias.toFixed(4)),
        hook: Number(hookBias.toFixed(4)),
        pacing: Number(pacingBias.toFixed(4)),
        alignment: Number(alignment.toFixed(4)),
        complexity: Number(complexity.toFixed(4)),
        overall: Number(overall.toFixed(4)),
      },
    });
  }

  return candidates;
}

function selectCandidate(candidates) {
  const selected =
    candidates.sort((left, right) => right.scoreBreakdown.overall - left.scoreBreakdown.overall)[0] ||
    null;

  return {
    selectedCandidateId: selected?.id || null,
    objective: 'Maximize retention, hook strength, pacing quality, and prompt alignment.',
    reason: selected
      ? `${selected.label} won because it produced the strongest weighted overall score without exceeding bounded graph complexity.`
      : 'No candidate was produced, so the optimizer selected nothing.',
    constraints: [
      'Keep variant count at or below four.',
      'Keep custom block creation at or below three.',
      'Preserve the current manual pipeline handlers.',
    ],
  };
}

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    res.setHeader('Allow', 'POST');
    res.status(405).json({ error: 'Method not allowed' });
    return;
  }

  try {
    const body = normalizeBody(req.body);
    const feature = cleanText(body.feature);
    const prompt = cleanText(body.prompt);
    const workflow = body.workflow ?? null;

    if (feature !== 'feature1' && feature !== 'feature2') {
      res.status(400).json({ error: 'Feature must be feature1 or feature2.' });
      return;
    }

    if (!prompt) {
      res.status(400).json({ error: 'Prompt is required.' });
      return;
    }

    if (!workflow || !Array.isArray(workflow.nodes) || !Array.isArray(workflow.edges)) {
      res.status(400).json({ error: 'Workflow graph is required.' });
      return;
    }

    const retrievalHits = await retrieveSimilar(prompt, feature);
    const agentPlan = await planWithWorkflowAgent({
      feature,
      prompt,
      workflow,
      retrievalHits,
    });
    const fallbackPlan = buildDeterministicPlan({
      feature,
      prompt,
      workflow,
    });
    const isExplicitGameplayRequest =
      feature === 'feature2' &&
      (hasExplicitGameplayChangeRequest(prompt) || wantsDifferentGameplayVariants(prompt));
    const isExplicitVoiceVariantRequest =
      feature === 'feature2' && hasExplicitVoiceVariantRequest(prompt);
    const shouldUseDeterministicGameplayFallback =
      isExplicitGameplayRequest && !planHandlesGameplayRequest(agentPlan);
    const shouldUseDeterministicVoiceFallback =
      isExplicitVoiceVariantRequest && !planHandlesVoiceVariantRequest(agentPlan);
    const shouldUseDeterministicFallback =
      shouldUseDeterministicGameplayFallback || shouldUseDeterministicVoiceFallback;
    const selectedPlan =
      shouldUseDeterministicFallback ? fallbackPlan : agentPlan || fallbackPlan;
    const plan = sanitizePlanForFeature({
      feature,
      prompt,
      workflow,
      plan: selectedPlan,
    });
    const validation = validatePlan(plan);
    const candidates = buildCandidates(prompt, plan.actions, feature);
    const optimization = selectCandidate(candidates);
    const userFacingSummary = buildUserFacingPlanSummary({
      feature,
      workflow,
      plan,
    });

    await persistMemory(feature, prompt, userFacingSummary, [
      feature,
      validation.ok ? 'validated' : 'fallback',
    ]);

    res.status(200).json({
      feature,
      model:
        shouldUseDeterministicFallback || !agentPlan
          ? 'deterministic-fallback'
          : agentPlan.modelLabel,
      fallbackUsed: shouldUseDeterministicFallback || !agentPlan,
      warning: shouldUseDeterministicFallback ? undefined : agentPlan?.warning,
      summary: userFacingSummary,
      validation,
      retrievalHits,
      actions: plan.actions,
      customBlocks: plan.customBlocks,
      candidates,
      optimization,
      execution: plan.execution,
    });
  } catch (error) {
    res.status(500).json({
      error: error instanceof Error ? error.message : 'Agent orchestration failed.',
    });
  }
}
